```name: aztec-prover
services:
  prover-node:
    image: aztecprotocol/aztec:latest # Always refer to the docs to check that you're using the correct image.
    entrypoint: >
      sh -c "node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --prover-node --archiver --network alpha-testnet"
    depends_on:
      broker:
        condition: service_started
        required: true
    environment:
      # PROVER_COORDINATION_NODE_URL: "http://:8080" # this can point to your own validator - using this replaces the need for the prover node to be on the P2P network and uses your validator as a sentry node of some sort.
      P2P_ENABLED: "true" # Switch to false if you provide a PROVER_COORDINATION_NODE_URL
      P2P_ANNOUNCE_ADDR: /ip4/<VPS_IP>/tcp/40400
      P2P_IP: <VPS_IP>
      DATA_DIRECTORY: /data
      DATA_STORE_MAP_SIZE_KB: "134217728"
      ETHEREUM_HOSTS: <RPC>
      L1_CONSENSUS_HOST_URLS: <BEACON_RPC>
      LOG_LEVEL: info
      PROVER_BROKER_HOST: http://broker:8080
      PROVER_PUBLISHER_PRIVATE_KEY: <PRIVATE_KEY>
    ports:
      - "8080:8080"
      - "40400:40400"
      - "40400:40400/udp"
    volumes:
      - /root/.aztec/alpha-testnet/data/:/data

  agent:
    image: aztecprotocol/aztec:latest # Always refer to the docs to check that you're using the correct image.
    entrypoint: >
      sh -c "node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --prover-agent --network alpha-testnet"
    environment:
      P2P_ANNOUNCE_ADDR: /ip4/<VPS_IP>/tcp/40400
      PROVER_AGENT_COUNT: "1"
      PROVER_AGENT_POLL_INTERVAL_MS: "10000" # Just to reduce the log spamming if you're using debug logging.
      PROVER_BROKER_HOST: http://broker:8080
      PROVER_ID: <WALLET_ADDRESS> # this should be the address corresponding to the PROVER_PUBLISHER_PRIVATE_KEY you set on the node.
    pull_policy: always
    restart: unless-stopped

  broker:
    image: aztecprotocol/aztec:latest # Always refer to the docs to check that you're using the correct image.
    entrypoint: >
      sh -c "node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --prover-broker --network alpha-testnet"
    environment:
      DATA_DIRECTORY: /data
      P2P_ANNOUNCE_ADDR: /ip4/<VPS_IP>/tcp/40400
      ETHEREUM_HOSTS: <RPC> # Your EL RPC endpoint
      LOG_LEVEL: info
    volumes:
      - /root/.aztec/alpha-testnet/data/:/data
```
